# Purpose: Downgrade the RDS instance class to something smaller for purposes of handling normal activity
#          without heavy data management processing.
# Key Dependencies:
#   - AWS CLI configured with AWS_ACCESS_KEY and AWS_SECRET_KEY available as environment variables to manage RDS service
#   - RDS options within task: instance_name, instance_type, parameter_group (optional)
---
- name: Downgrade Database Instance Class
  hosts: localhost
  gather_facts: no
  tasks:
    - rds:
        command: modify
        instance_name: REPLACEME
        instance_type: REPLACEME
        parameter_group: REPLACEME
        apply_immediately: yes
        wait: yes
