# Purpose: Add storage to SAS CAS primary controller for SAS datasets or other flat files.
# Key Dependencies:
#   - Become ROOT user (to install packages with yum)
#   - SAS Viya deployment inventory file
#   - Standard yum repositories available to download mdadm
#   - Set YAML variable: "sascache_owner" and "sascache_group" for target filesystem permissions
---
- name: Setup SASDATA on programming environment server
  hosts: programming
  gather_facts: false
  become: true
  become_user: root
  vars:
    sasdata_owner: sas
    sasdata_group: sas
  tasks:
    - name: Install MDADM
      yum:
        name: mdadm
        state: latest

    # NOTE: Confirm RAID and device configuration for target environment.
    - name: Configure RAID0
      command: mdadm --create --verbose /dev/md0 --level=0 --name=SASDATA --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1

    - name: Reload info for kernel
      shell: dracut -H -f /boot/initramfs-$(uname -r).img $(uname -r)

    # NOTE: Confirm filesystem options for target environment
    - name: Make XFS Filesystem for SASDATA
      command: mkfs.xfs -L SASDATA -i size=512 -b size=4096 -d sunit=1024,swidth=4096 /dev/md0

    - name: Mount Filesystem to SASDATA
      mount:
        path: /sasdata
        src: /dev/md0
        fstype: xfs
        opts: noatime,nodiratime,nobarrier,nofail
        state: mounted

    - name: Update permissions and ownership for SASDATA
      file:
        path: /sasdata
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    # NOTE: The next series of tasks setup a common directory structure for organizing files under a mock "project1".
    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1/dq_check
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1/err
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1/log
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1/source
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Setup project1 directory structure
      file:
        path: /sasdata/project1/stage
        state: directory
        owner: "{ sasdata_owner }"
        group: "{ sasdata_group }"
        mode: 0775

    - name: Reload Daemon to prevent creation refresh problems
      command: systemctl daemon-reload
